name: SkyWars
main: com.comze_instancelabs.skywars.Main
version: 1.1
author: instancelabs
softdepend: [Vault]
commands:
   skywars:
      description: Main command
      usage: /skywars <action>
      aliases: [sw]

